name: (M) Create Release
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  release:
    name: Tag code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Create/push tag
        run: |
          mkdir /tmp/dingo
          cp -R * /tmp/dingo
          home=$(pwd)
          cd /tmp/dingo
          npm install
          npm run build
          rm -fR node_modules
          cd ../
          zip dingo.zip dingo
          ls
          cd $home
        env:
          set_version: ${{ github.event.inputs.version }}
          username: ${{ secrets.GIT_USER }}
          email: ${{ secrets.GIT_EMAIL }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
